# Generated by Django 4.1.1 on 2022-10-03 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minha_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name="vendas",
            name="data",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 3, 11, 6, 2, 653054)
            ),
        ),
        migrations.AlterField(
            model_name="vendedor",
            name="nome",
            field=models.CharField(max_length=70),
        ),
    ]
