# Generated by Django 4.1.1 on 2022-10-03 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minha_dashboard", "0002_alter_produto_nome_alter_vendas_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendas",
            name="data",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 3, 11, 11, 54, 511796)
            ),
        ),
    ]
